<?php

return [
    'index_title' => 'Aids',
    'index_subtitle' => 'View and manage all aids',
    'create_title' => 'Create New Aid',
    'create_subtitle' => 'Create a new aid for a beneficiary',
    'edit_title' => 'Edit Aid',
    'edit_subtitle' => 'Update aid details',
    'create_button' => 'New Aid',

    'field_title' => 'Title',
    'field_title_hint' => 'An optional label for this aid (e.g. "Rent payment — July"). Shown in the header and lists.',
    'field_title_placeholder' => 'Optional aid title',
    'field_beneficiary' => 'Beneficiary',
    'field_beneficiaries' => 'Beneficiaries',
    'field_program' => 'Program',
    'field_type' => 'Aid Type',
    'field_amount' => 'Amount',
    'field_purpose' => 'Purpose',
    'field_items' => 'Items',
    'field_item_name' => 'Item Name',
    'field_item_quantity' => 'Quantity',
    'field_item_estimated_value' => 'Estimated Value',
    'field_item_description' => 'Description',
    'field_notes' => 'Notes',
    'field_reference' => 'Reference',
    'field_status' => 'Status',
    'field_current_stage' => 'Current Stage',
    'field_created_at' => 'Created At',
    'field_created_by' => 'Created By',
    'field_decision_note' => 'Decision Note',
    'decision_note_hint' => 'Add a note explaining the reason (required for rejection and return)',

    'select_placeholder' => 'Select from the list',
    'search_placeholder' => 'Search by reference or beneficiary name...',
    'beneficiary_search_placeholder' => 'Search by name or national ID...',
    'picker_placeholder' => 'Search and select beneficiaries',
    'no_results' => 'No beneficiaries match your search',
    'select_all' => 'Select All',
    'clear_selection' => 'Clear Selection',
    'select_all_capped' => 'Only the first :count beneficiaries in the current search results were selected (the maximum for a single bulk selection). Narrow your search to select the rest.',
    'selected_count' => '{0} No beneficiary selected yet|{1} 1 beneficiary selected|[2,*] :count beneficiaries selected',
    'bulk_create_hint' => 'An independent aid will be created for each of the :count selected beneficiaries, using the same data entered above.',

    'type_cash' => 'Cash Aid',
    'type_cash_hint' => 'Provide a specific amount in Saudi Riyals',
    'type_in_kind' => 'In-Kind Aid',
    'type_in_kind_hint' => 'Provide specific goods or services',

    'currency_sar' => 'SAR',

    'add_item' => 'Add Item',
    'no_items_yet' => 'No items added yet',

    'save_draft' => 'Save as Draft',
    'save_and_submit' => 'Save and Submit for Approval',
    'submit_button' => 'Submit for Approval',

    'confirm_submit' => 'Are you sure you want to submit this aid for approval?',

    'submit_confirm' => [
        'title' => 'Save & submit for approval',
        'subtitle' => 'Review the details below before saving and sending into the approval workflow.',
        'bulk_note' => ':count separate aids will be created and submitted, one per selected beneficiary.',
        'items_count' => '{1} 1 item|[2,*] :count items',
        'recurring_note' => 'A recurring schedule will be attached: :frequency, starting :date.',
        'none' => '—',
    ],

    'recurring_series' => [
        'badge' => 'Part of a recurring series',
        'title' => 'Recurring aid',
        'origin' => 'This aid originates a recurring series.',
        'instance' => 'This aid was generated by a recurring plan.',
        'view_plan' => 'View the plan',
        'cycle' => 'Cycle :n',
    ],
    'confirm_cancel' => 'Are you sure you want to cancel this aid?',
    'confirm_delete' => 'Are you sure you want to delete this aid?',
    'confirm_decision' => 'Are you sure about this decision?',

    'submit_modal' => [
        'title' => 'Submit Aid for Approval',
        'subtitle' => 'Review the summary below before sending this aid into the approval workflow.',
        'notify_title' => 'What happens on submission',
        'notify_stage' => 'The aid moves to the "‎:stage‎" stage for review by the :role.',
        'notify_recipients' => '{1} One active reviewer will be notified.|[2,*] :count active reviewers will be notified.',
        'notify_none' => 'No active user holds this role yet — no one will be notified until the role is assigned.',
        'channel_bell' => 'In-app notification',
        'channel_email' => 'Email',
        'no_flow' => 'No active approval flow applies to this aid; it cannot be submitted until stages are configured.',
    ],

    'decision_modal' => [
        'title' => 'Confirm decision: :action',
        'subtitle' => 'Review the effect of this decision before confirming.',
        'effect_title' => 'Effect of this decision',
        'approve_next' => 'The aid moves to the "‎:stage‎" stage for review by the :role.',
        'approve_final' => 'The aid is finally approved and the beneficiary is notified by SMS/WhatsApp.',
        'reject_effect' => 'The aid is rejected and moves to the final "Rejected" status. No notification is sent.',
        'return_effect' => 'The aid returns to "Draft" for its creator to revise and resubmit. No notification is sent.',
    ],

    'cancel_modal' => [
        'title' => 'Cancel Aid',
        'subtitle' => 'This aid will be cancelled and cannot be undone. No notification is sent.',
        'confirm_button' => 'Confirm Cancellation',
    ],

    'no_actions_available' => 'No actions available at this time',

    'returned_notice_title' => 'This aid was returned for revision',

    'details_title' => 'Details',
    'progress_title' => 'Progress',
    'decisions_title' => 'Decisions',
    'actions_title' => 'Actions',

    'items_total' => 'Total',
    'items_count' => '{0} no items|{1} one item|[2,*] :count items',

    'filter_status' => 'Filter by Status',
    'filter_program' => 'Filter by Program',
    'filter_type' => 'Filter by Type',
    'filter_receipt' => 'Receipt Status',

    'results_count' => '{0} No results|{1} 1 result|[2,*] :count results',

    'empty_title' => 'No Aids',
    'empty_description' => 'Start by creating a new aid for your beneficiaries',

    'status' => [
        'draft' => 'Draft',
        'submitted' => 'Submitted',
        'under_review' => 'Under Review',
        'approved' => 'Approved',
        'in_disbursement' => 'In Disbursement',
        'delivered' => 'Delivered',
        'confirmed' => 'Receipt Confirmed',
        'rejected' => 'Rejected',
        'cancelled' => 'Cancelled',
    ],

    'type' => [
        'cash' => 'Cash',
        'in_kind' => 'In-Kind',
    ],

    'program_type' => [
        'cash' => 'Cash Only',
        'in_kind' => 'In-Kind Only',
        'both' => 'Cash and In-Kind',
    ],

    'documents' => [
        'title' => 'Supporting Documents',
        'hint' => 'Attach documents (PDF, JPG or PNG, up to 5 MB each).',
        'uploading' => 'Uploading...',
        'pending_count' => '{1} 1 file ready to upload|[2,*] :count files ready to upload',
    ],

    'recurrence' => [
        'card_title' => 'Recurring aid',
        'card_subtitle' => 'Schedule this aid to be created automatically at regular intervals.',
        'enable' => 'Make this a recurring aid',
        'enable_hint' => 'Automatically create a new aid on a schedule.',
        'frequency_label' => 'Frequency',
        'interval_months' => 'Months between each occurrence',
        'starts_on' => 'Schedule start date',
        'starts_on_hint' => 'When the schedule becomes active — no aid is generated before this date.',
        'due_on' => 'First due date',
        'due_on_hint' => 'The first entitlement (due) date. Leave empty to use the start date.',
        'ends_on' => 'End date (optional)',
        'ends_on_hint' => 'Leave empty to recur indefinitely.',
        'lead_days' => 'Lead days',
        'lead_days_hint' => 'Days before the due date the aid is generated (0 = on the due date itself).',
        'title_template' => 'Title template (optional)',
        'title_template_hint' => 'Titles each generated aid. Placeholders: {program}, {beneficiary}, {month}, {year}, {n}.',
        'title_preview' => 'Preview:',
        'title_use_default' => 'Use default template',
        'active' => 'Schedule active',
        'active_hint' => 'Turn off to pause recurrence without deleting it.',
        'frequency' => [
            'monthly' => 'Monthly',
            'quarterly' => 'Quarterly',
            'semi_annual' => 'Semi-annual',
            'yearly' => 'Yearly',
            'custom_months' => 'Custom (months)',
        ],
    ],

    'messages' => [
        'submitted' => 'Aid submitted successfully for approval',
        'saved' => 'Aid saved successfully',
        'deleted' => 'Aid deleted successfully',
        'cancelled' => 'Aid cancelled successfully',
        'bulk_created' => ':count aids created successfully, one independent aid per beneficiary',
        'bulk_submitted' => ':count aids submitted successfully for approval',
    ],

    'programs' => [
        'messages' => [
            'saved' => 'Aid program saved successfully',
            'cannot_delete_in_use' => 'Cannot delete an aid program that is in use',
            'deleted' => 'Aid program deleted successfully',
        ],
    ],
];
