<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Aid title + recurring due-date/title-template support.
 *
 * - aids.title: an optional custom label for an aid (shown in the header,
 *   the submit-confirm modal, and lists). For aids generated by a recurring
 *   plan this is filled from the plan's title_template.
 * - recurring_aid_plans.title_template: a template rendered into each
 *   generated aid's title (placeholders {program}/{beneficiary}/{month}/
 *   {year}/{n}).
 * - recurring_aid_plans.due_on: the first entitlement/due date (تاريخ
 *   الاستحقاق), kept distinct from starts_on (تاريخ البدء = when the schedule
 *   becomes active / the earliest a cycle may be generated). Null on legacy
 *   rows falls back to starts_on.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('aids', function (Blueprint $table): void {
            $table->string('title')->nullable()->after('reference');
        });

        Schema::table('recurring_aid_plans', function (Blueprint $table): void {
            $table->string('title_template')->nullable()->after('interval_months');
            $table->date('due_on')->nullable()->after('starts_on');
        });
    }

    public function down(): void
    {
        Schema::table('aids', function (Blueprint $table): void {
            $table->dropColumn('title');
        });

        Schema::table('recurring_aid_plans', function (Blueprint $table): void {
            $table->dropColumn(['title_template', 'due_on']);
        });
    }
};
